[package]
name = "hello_world"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ["cdylib"] # 创建动态链接库 （C-compatible dynamic library ）

[dependencies.uuid]
version = "1.18.1"
# Lets you generate random UUIDs
features = [
    "v4",
    "js",
]

[dependencies]
wasm-bindgen = "0.2.105"
