[package]
name = "clip_demo"
version = "0.1.0"
edition = "2024"


[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
console = "0.16.1"
dialoguer = "0.12.0"
add = { path = "../add" }
